### ISSUE TITLE
the question of result

### ISSUE THREAD

**Issue by maxiang0305** [gggliuye/VINS_BASTIAN#1]
Could you tell me the result of the code? Can I get the transfer matrix from imu data?

**Comment by gggliuye** [comment]
Sorry I forgot to put some example.
Now you can see example videos in readme.

As is shown, we could have the camera pose + map points.

This is a VIO system, it offers camera pose as output.
(currently I implement the output at camera frequency. but you can easily change it to IMU frequency, by applying IMU propagation)
cannot get rigid pose from only IMU.
